install {
  /setblock ${origin + (-2 0 0)} command_block 0 replace {Command:"execute @e[name=mpl_tests] ~ ~ ~ setblock ~ ~ ~ redstone_block"}
  /scoreboard objectives add MplTest dummy
  /scoreboard objectives setdisplay sidebar MplTest
}

uninstall {
  /scoreboard objectives remove MplTest
  /kill @e[name=continue_tests]
}

impulse process mpl_tests {
  /say starting mpl test
  /scoreboard players set MplTestFailed MplTest 0
  /scoreboard players set MplTestCount MplTest 0

  // autogenerated by for
  /scoreboard players tag @e[tag=Test] add param
  // autogenerated by for
  while: /testfor @e[tag=param]
  repeat {
    // autogenerated by for
    /scoreboard players tag @e[tag=param,c=1] add current
    // autogenerated by for
    /scoreboard players tag @e[tag=current] remove param

    /scoreboard players add MplTestCount MplTest 1
    /tellraw @a [{"text":"Starting "},{"selector":"@e[tag=current]","color":"yellow"}]
    start @e[tag=current]
    waitfor continue_tests
    /kill @e[name=continue_tests]

    // autogenerated by for
    /scoreboard players tag @e[tag=current] remove current

    if: /scoreboard players test MplTestFailed MplTest 1 *
    then {
      break
    }
  }
  if not: /scoreboard players test MplTestFailed MplTest 1 *
  then {
    /tellraw @p [{"text":"ALL ","color":"green"},{"score":{"name":"MplTestCount","objective":"MplTest"},"color":"green"},{"text":" TESTS SUCCESSFUL!!!","color":"green"}]
  } else {
    /tellraw @p [{"text":"There were failing tests","color":"red"}]
  }
}

impulse process fail {
  /tellraw @p [{"text":"TEST FAILED","color":"red"}]
  /scoreboard players set MplTestFailed MplTest 1
  notify continue_tests
}
